version: 0.0
os: linux
files:
  - source: /html.tar.gz
    destination: /var/www/charmingcharlie/
hooks:
  BeforeInstall:
    - location: scripts/configure_nfs
      timeout: 300
      runas: root
    - location: scripts/sync_media
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_magento
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
      runas: root
